@startuml
actor Utente
participant "Sistema" as Sistema
participant "MotoreDomande" as Motore
participant "InterfacciaDomande" as UI
participant "StatisticaManager" as StatManager


Sistema -> Motore : analizza il testo del documento
Motore -> Motore : genera le domande in base al testo
Motore --> Sistema : lista delle domande

loop Per ogni domanda
    Sistema -> UI : mostra la domanda con le risposte
    Utente -> UI : seleziona la risposta
    UI -> Sistema : salva la risposta
end

Sistema -> StatManager : calcola il punteggio
StatManager --> Sistema : calcola le statistiche
Sistema -> UI : mostra il punteggio e le statistiche

@enduml