@startuml
actor Utente
participant "View" as UI
participant "AuthController" as Controller
participant "AuthService" as Service
database "UserDAO (Database)" as DB

== Registrazione Utente ==
Utente -> UI : compila form con username e password

UI -> Controller : handleRegisterBtn()
Controller -> Service : register(username, password, noUsers)
Service -> DB : selectById(username)
DB --> Service : Optional.empty() // username non esistente
Service -> DB : insert(User)
Service -> Controller : true
Controller -> UI : ViewLoader.load(MENU)

== Flusso Alternativo ==
group Username già esistente
UI -> Controller : handleRegisterBtn()
Controller -> Service : register(username, password, noUsers)
Service -> DB : selectById(username)
DB --> Service : Optional.of(User) // username esistente
Service -> Controller : false
Controller -> UI : showDialog(ERROR, "L'utente esiste già")
end

@enduml

