@startuml
set namespaceSeparator none
package it.unisa.diem.wordageddon_g16 {
    package controllers{}
    package db{}
    package models{}
    package services{}
    package utility{}
    class WordageddonApp {
      + WordageddonApp():
      + start(Stage): void
      + main(String[]): void
    }
}
@enduml