@startuml
actor Utente
participant AuthController
participant AppContext
participant AuthService
database "UserDAO (Database)" as DB
participant View

activate Utente
Utente -> AuthController : inserisce username e password
activate AuthController

AuthController -> AppContext : getAuthService()
activate AppContext
AppContext --> AuthController : return AuthService
deactivate AppContext

AuthController -> AuthService : login(username, password)
activate AuthService

AuthService -> DB : selectById(username)
activate DB


DB --> AuthService : return User
deactivate DB

AuthService -> AuthService : verifica password

alt login valido

    AuthService -> AppContext : setCurrentUser(user)
    activate AppContext
    deactivate AppContext
    AuthService->AuthService: saveSession(user)
    AuthService --> AuthController : ritorna true
    AuthController -> View : carica schermata MainMenu
    activate View
    deactivate View
else login fallito
    AuthService --> AuthController : return false
    AuthController -> View :  showDialog()
    note right of AuthController
        Mostra messaggio di errore all'utente
    end note
    activate View
    deactivate View
end

deactivate AuthService
deactivate AuthController
deactivate Utente
@enduml