@startuml
actor Utente
participant AuthController
participant AppContext
participant AuthService
database "Database/DAO" as DB
participant View

activate Utente
Utente -> AuthController : inserisce username e password
activate AuthController

AuthController -> AppContext : getAuthService()
activate AppContext
AppContext --> AuthController : return AuthService
deactivate AppContext

AuthController -> AuthController : handleLogin()
activate AuthController #3375E0
AuthController -> AuthService : login()
activate AuthService
AuthService -> AuthService : login()
activate AuthService #3375E0
AuthService -> DB : selectBy()

activate DB

DB --> AuthService : User
deactivate DB
deactivate AuthService

AuthService --> AuthController : boolean
deactivate AuthService

alt true
    AuthService -> AppContext : setCurrentUser(user)
    activate AuthService
    activate AppContext
    deactivate AppContext
    AuthService->AuthService: saveSession(user)
    AuthController -> View : ViewLoader(MENU)
    deactivate AuthService
    activate View
    deactivate View
else false
    AuthController -> View :  showDialog()
    deactivate AuthController
    View --> Utente : Dialog("Login fallito")
    note right of AuthController
        Mostra messaggio di errore all'utente
    end note
    activate View  #3375E0
    deactivate View
end

deactivate AuthService
deactivate AuthController
deactivate Utente
@enduml