@startuml
actor Amministratore
participant UserPanelController
participant UserPanelService
database "Database/DAO" as DB
participant View

activate Amministratore
activate View
Amministratore -> View : "Carica un documento"
UserPanelController -> UserPanelController : handleDocumenti()
activate UserPanelController

activate UserPanelController #3375E0
UserPanelController -> UserPanelService :moveDocument()
activate UserPanelService
activate UserPanelService #3375E0
UserPanelService -> DB : SelectBy()
activate DB
DB --> UserPanelService : Document
deactivate UserPanelService
deactivate DB
opt Documento giá presente
    UserPanelController -> View : showDialog()
    View -> Amministratore: Dialog("Documento giá presente")
        note right
            "Mostra messaggio di errore all'utente"
        end note
end

UserPanelController -> UserPanelService : updateWDM()
deactivate UserPanelController

activate UserPanelService #3375E0
UserPanelService -> DB : selectBy()
activate DB
DB --> UserPanelService : WDM
deactivate DB
alt WDM giá presente
UserPanelService -> DB : DocumentUpdate()
UserPanelService -> DB : WDMUpdate()
else #orange else
    UserPanelService -> DB : DocumentInsert()
    UserPanelService -> DB : WDMInsert()
end
deactivate UserPanelService
UserPanelController -> View : aggiorna vista
deactivate UserPanelController
@enduml

