@startuml
actor Amministratore
participant UserPanelController
participant UserPanelService
database "Database/DAO" as DB
participant View

activate Amministratore
activate View
Amministratore -> View : "Inserisce stopwords manualmente"
UserPanelController -> UserPanelController : handleStopWords()
activate UserPanelController

UserPanelController -> UserPanelService :addStopWords()
activate UserPanelController #3375E0

UserPanelService -> UserPanelService : stopWordsParser()


deactivate UserPanelController
activate UserPanelService
UserPanelService -> DB : insert()

activate DB

deactivate UserPanelService
deactivate UserPanelController
deactivate DB
Amministratore -> View : "Carica file di stopwords"
UserPanelController -> UserPanelController : handleStopWords()
activate UserPanelController
UserPanelController -> UserPanelService : addStopWordsFromFile()
loop for each line
    UserPanelService -> UserPanelService : stopWordsParser()
    UserPanelService -> DB : insert()
end
@enduml

