name: Deploy Javadoc

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy javadoc to Github Pages
        uses: dev-vince/actions-publish-javadoc@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: "24"               # Modifica la versione se necessario
          java-distribution: "temurin"       # O "temurin" per Java 21+
          project: maven                   # O "gradle" se usi Gradle
          branch: "gh-pages"               # Branch dove vuoi pubblicare la doc Javadoc
