name: Deploy Full Javadoc

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'   

      - name: Generate Javadoc (tutti i package, anche privati)
        run: |
          mkdir -p docs/Javadoc
          javadoc -d docs/Javadoc \
            -sourcepath src/main/java \
            -subpackages it.unisa.diem.wordageddon_g16 \
            -private

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/Javadoc
